// <auto-generated />
using System;
using ECommerceSaga.Inventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ECommerceSaga.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ECommerceSaga.Inventory.Infrastructure.Persistence.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReservedStock")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStock")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("a1b2c3d4-e5f6-4789-a012-345678901234"),
                            ProductName = "Product 1",
                            ReservedStock = 0,
                            TotalStock = 50
                        },
                        new
                        {
                            ProductId = new Guid("b2c3d4e5-f6a7-4890-b123-456789012345"),
                            ProductName = "Product 2",
                            ReservedStock = 0,
                            TotalStock = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
